paginate: 10                              # pagination basted on number of posts
title: 84 Precious Words
email: churchinirvine@gmail.com
description: >                            # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://yourdomain.com"              # the base hostname & protocol for your site
twitter_username: bibles4america
github_username:  biblesforamerica 
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss']

collections:
  words:
    output: true
defaults:
  -
    scope:
      path: ""
      type: "drafts"
    values:
      category-heading: Words that Describe Our Personal Fellowship with the Lord
# Build settings
markdown: redcarpet
recarpet:
  extensions: ["smart", "superscript"]